os: linux
dist: bionic
language: python
sudo: required
services:
  - xvfb
after_failure: >
  if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"Webots need your Help! Nightly build failed during the '$(echo $TRAVIS_BUILD_STAGE_NAME)' stage on the '$(echo $TRAVIS_BRANCH)' branch: $(echo $TRAVIS_BUILD_WEB_URL)\" }" $DISCORD_WEBHOOK; fi
jobs:
  include:
    - &test_suite
      stage: Test Suite
      name: Test Suite
      install:
        - pip install -r tests/requirements.txt
      script:
        - python -m unittest discover -s tests
    - &build
      if: type = cron OR type = api OR tag IS present
      stage: Build
      name: Build $WEBOTS_TARGET_BRANCH_0
      addons:
        apt:
          packages:
            - build-essential
            - cmake
            - curl
            - execstack
            - ffmpeg
            - git
            - libassimp-dev
            - libavcodec-extra
            - libboost-dev
            - libfreeimage-dev
            - libfreetype6-dev
            - libgd-dev
            - libglib2.0-dev
            - libglu1-mesa-dev
            - libreadline-dev
            - libssh-4
            - libssh-gcrypt-dev
            - libssl1.1
            - libusb-dev
            - libxcb-icccm4
            - libxcb-image0
            - libxcb-keysyms1
            - libxcb-randr0
            - libxcb-render-util0
            - libxcb-xinerama0
            - libxml2-dev
            - libxslt1.1
            - libzip-dev
            - libzzip-0-13
            - lsb-release
            - libssl1.0-dev  # dependency of npm
            - nodejs-dev     # dependency of npm
            - node-gyp       # dependency of npm
            - npm
            - openjdk-11-jdk
            - pbzip2
            - python-pip
            - python2.7-dev
            - python3.6-dev
            - python3.7-dev
            - python3.8-dev
            - swig
            - unzip
            - wget
            - xvfb
            - zip
      before_install:
        - sudo snap install snapcraft --classic
        - pip install PyGithub # used to upload packages to Github releases
      install:
        - git clone --recurse-submodules --depth 3 --single-branch --branch $WEBOTS_TARGET_BRANCH_0 https://github.com/cyberbotics/webots.git
        - ./webots/scripts/linux_optional_compilation_dependencies.sh
      script:
        - export COMMIT_ID=$(cd webots; git rev-parse HEAD)
        - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then python webots/scripts/packaging/set_commit_and_date_in_version.py $COMMIT_ID; fi
        - travis_wait 40 sudo snapcraft --destructive-mode
        - cp *.snap webots/distribution
        - webots/scripts/packaging/publish_release.py --key=$GITHUB_API_KEY --repo=cyberbotics/webots --branch=$WEBOTS_TARGET_BRANCH_0 --commit=$COMMIT_ID --tag=$TRAVIS_TAG
    - <<: *build
      name: Build $WEBOTS_TARGET_BRANCH_1
      install:
        - git clone --recurse-submodules --depth 3 --single-branch --branch $WEBOTS_TARGET_BRANCH_1 https://github.com/cyberbotics/webots.git
        - ./webots/scripts/linux_optional_compilation_dependencies.sh
        - sed -i 's/R2020b-rev1/R2021a/g' snapcraft.yaml
      script:
        - export COMMIT_ID=$(cd webots; git rev-parse HEAD)
        - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then python webots/scripts/packaging/set_commit_and_date_in_version.py $COMMIT_ID; fi
        - travis_wait 40 sudo snapcraft --destructive-mode
        - cp *.snap webots/distribution
        - webots/scripts/packaging/publish_release.py --key=$GITHUB_API_KEY --repo=cyberbotics/webots --branch=$WEBOTS_TARGET_BRANCH_1 --commit=$COMMIT_ID --tag=$TRAVIS_TAG
